version: '3.8'

services:
  app:
    build: .
    container_name: securex_app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/securex
      - JWT_SECRET=production_docker_secret_securex_2026
      - TOTP_ISSUER=SecureX
      - CORS_ORIGIN=*
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

  mongo:
    image: mongo:7-jammy
    container_name: securex_mongo
    ports:
      - "27017:27017"
    volumes:
      - securex_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped

volumes:
  securex_data:
    driver: local
